data:
  title_size: 30
  his_size: 50
  dict_size: 1000
  npratio: 4
  pop: 0
  fresh: 0
  
info:
  metrics:
  - auc
  - mrr
  - ndcg@5
  - ndcg@10

model:
  global: False # True
  attention_hidden_dim: 200
  word_emb_dim: 300
  dropout: 0.25
  head_num: 20
  head_dim: 20

train:
  seed: 42
  batch_size: 64 # 128
  epochs: 15
  learning_rate: 0.0002 # 0.0001
  weight_decay: 0
  num_cores: 10

