data:
  title_size: 30
  his_size: 30 # 50
  npratio: 4
  pop: 7
  fresh: 1
  
info:
  metrics:
  - auc
  - mrr
  - ndcg@5
  - ndcg@10

model:
  global: True
  attention_hidden_dim: 200 # 200
  word_emb_dim: 312 # tiny bert: (312)
  dropout: 0.3 #0.2
  head_num: 15 # 20
  head_dim: 15 # 20

train:
  seed: 42
  batch_size: 25 # 128
  epochs: 1000
  learning_rate: 0.0001
  weight_decay: 0
  num_cores: 2
