data:
  title_size: 30
  abstract_size: 30
  his_size: 40
  npratio: 4
  bucket_size: 3
  pop: 0
  fresh: 0

info:
  metrics:
  - auc
  - mrr
  - ndcg@5
  - ndcg@10

model:
  global: False
  aux: True
  attention_hidden_dim: 200
  word_emb_dim: 300
  cat_emb_dim: 100
  dropout: 0.2
  head_num: 20
  head_dim: 20
  text_self_attn_layer: 2
  history_self_attn_layer: 1

train:
  seed: 0
  batch_size: 128
  epochs: 30
  learning_rate: 0.0001
  weight_decay: 0
